import psycopg2
from errors import CacheException
import json
 

class FilesCacheManager:
    def __init__(self, db_params:json):
        self.db_params = db_params

    
    def get_file_details_from_db(self, file_hash:str):
        try:
            with psycopg2.connect(**self.db_params) as conn:
                cursor = conn.cursor()
                cursor.execute("SELECT * FROM android_apps_cache_files WHERE file_hash = %s", (file_hash,))
                existing_item = cursor.fetchone()
                cursor.close()
                return existing_item
        except Exception as e:
            raise CacheException(f"Error occurred while run get_file_details_from_db: {e}")



    def insert_results_to_db(self, file_hash:str, verdict:str, probability:float, permissions:str):
        try:    
            with psycopg2.connect(**self.db_params) as conn:
                cursor = conn.cursor()
                query = f"INSERT INTO android_apps_cache_files (file_hash, verdict, probability, permissions) VALUES ('{file_hash}','{verdict}',{probability},'{permissions}');"
    
                cursor.execute(query)
                conn.commit()
                cursor.close()
        except Exception as e:
            raise CacheException(f"Error occurred while run insert_results_to_db: {e}")





    
    
    


    
   

    